matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '10'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - GH_TOKEN=vFFnYRjHwUpjxIQ55LUEuTPbVMTi8yNODVoBfEBBcf0qla7SfPhFXPa0iNbaylE1uz+6nIgCI5MY0Xmi8EUSuv0ff/MnlMUteTngrScqXJ5Py6hafzsm/6W1dQhV4yypudMrd1AhzTj7c3fAKNg2xY/bHH5CTZ76qpWyoUNkAgaam+/EVPnhyUwrW4qt2nY4gK3YXR2TaewUzNPXuGRCZrVdyA/vnNFvrjeP7KwQYJ5ye2h7uAEDIGZO8t5AqkMJqLWYRNiYyyIrWUQhCYTb3PnHve34t0yOa4+iJQTaTY6gFbVGnFZfhGM4yzpiRIK0+Mfto+URhYkO70zGFWl3uKIDYgt8V4RpEjXGnL7XnW6vbR3GgI+8ZRJiACpMqVV3mKsX7RbSnUVi1KhqVI9uLh7/fObVySLGtmlCIGKh36pYs6X7mrF+DoIYGuJjhpnA5Ae0yzlqr5NGxr3l6DST38+aU33sJ/OROwwsKL1aiTyI2xAboOcu09Sw/oT8T7ERj7c8ueVA8/v7q8UayGcQ+qqXLmeqwl90EkVSPAIQhlykoF7KIr+jXyb6L7RbohRYs8DviubVzWO+4Y7RIwvD4005UyuOIMWOSYBNYtxqnvSEPSAwnwvEMtQfAPZrLuWgJlwh2z1z7E2srFOZ1dk6WQtRYjOYwwKglzEr8AxTYZk=
  - os: linux
    services: docker
    language: node_js
    node_js: '10'
    env:
    - GH_TOKEN=vFFnYRjHwUpjxIQ55LUEuTPbVMTi8yNODVoBfEBBcf0qla7SfPhFXPa0iNbaylE1uz+6nIgCI5MY0Xmi8EUSuv0ff/MnlMUteTngrScqXJ5Py6hafzsm/6W1dQhV4yypudMrd1AhzTj7c3fAKNg2xY/bHH5CTZ76qpWyoUNkAgaam+/EVPnhyUwrW4qt2nY4gK3YXR2TaewUzNPXuGRCZrVdyA/vnNFvrjeP7KwQYJ5ye2h7uAEDIGZO8t5AqkMJqLWYRNiYyyIrWUQhCYTb3PnHve34t0yOa4+iJQTaTY6gFbVGnFZfhGM4yzpiRIK0+Mfto+URhYkO70zGFWl3uKIDYgt8V4RpEjXGnL7XnW6vbR3GgI+8ZRJiACpMqVV3mKsX7RbSnUVi1KhqVI9uLh7/fObVySLGtmlCIGKh36pYs6X7mrF+DoIYGuJjhpnA5Ae0yzlqr5NGxr3l6DST38+aU33sJ/OROwwsKL1aiTyI2xAboOcu09Sw/oT8T7ERj7c8ueVA8/v7q8UayGcQ+qqXLmeqwl90EkVSPAIQhlykoF7KIr+jXyb6L7RbohRYs8DviubVzWO+4Y7RIwvD4005UyuOIMWOSYBNYtxqnvSEPSAwnwvEMtQfAPZrLuWgJlwh2z1z7E2srFOZ1dk6WQtRYjOYwwKglzEr8AxTYZk=
  - os: windows
    language: node_js
    node_js: '10'
    env:
    - GH_TOKEN=vFFnYRjHwUpjxIQ55LUEuTPbVMTi8yNODVoBfEBBcf0qla7SfPhFXPa0iNbaylE1uz+6nIgCI5MY0Xmi8EUSuv0ff/MnlMUteTngrScqXJ5Py6hafzsm/6W1dQhV4yypudMrd1AhzTj7c3fAKNg2xY/bHH5CTZ76qpWyoUNkAgaam+/EVPnhyUwrW4qt2nY4gK3YXR2TaewUzNPXuGRCZrVdyA/vnNFvrjeP7KwQYJ5ye2h7uAEDIGZO8t5AqkMJqLWYRNiYyyIrWUQhCYTb3PnHve34t0yOa4+iJQTaTY6gFbVGnFZfhGM4yzpiRIK0+Mfto+URhYkO70zGFWl3uKIDYgt8V4RpEjXGnL7XnW6vbR3GgI+8ZRJiACpMqVV3mKsX7RbSnUVi1KhqVI9uLh7/fObVySLGtmlCIGKh36pYs6X7mrF+DoIYGuJjhpnA5Ae0yzlqr5NGxr3l6DST38+aU33sJ/OROwwsKL1aiTyI2xAboOcu09Sw/oT8T7ERj7c8ueVA8/v7q8UayGcQ+qqXLmeqwl90EkVSPAIQhlykoF7KIr+jXyb6L7RbohRYs8DviubVzWO+4Y7RIwvD4005UyuOIMWOSYBNYtxqnvSEPSAwnwvEMtQfAPZrLuWgJlwh2z1z7E2srFOZ1dk6WQtRYjOYwwKglzEr8AxTYZk=
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- npm run build
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
deploy:
  provider: releases
  api_key:
    secure: vFFnYRjHwUpjxIQ55LUEuTPbVMTi8yNODVoBfEBBcf0qla7SfPhFXPa0iNbaylE1uz+6nIgCI5MY0Xmi8EUSuv0ff/MnlMUteTngrScqXJ5Py6hafzsm/6W1dQhV4yypudMrd1AhzTj7c3fAKNg2xY/bHH5CTZ76qpWyoUNkAgaam+/EVPnhyUwrW4qt2nY4gK3YXR2TaewUzNPXuGRCZrVdyA/vnNFvrjeP7KwQYJ5ye2h7uAEDIGZO8t5AqkMJqLWYRNiYyyIrWUQhCYTb3PnHve34t0yOa4+iJQTaTY6gFbVGnFZfhGM4yzpiRIK0+Mfto+URhYkO70zGFWl3uKIDYgt8V4RpEjXGnL7XnW6vbR3GgI+8ZRJiACpMqVV3mKsX7RbSnUVi1KhqVI9uLh7/fObVySLGtmlCIGKh36pYs6X7mrF+DoIYGuJjhpnA5Ae0yzlqr5NGxr3l6DST38+aU33sJ/OROwwsKL1aiTyI2xAboOcu09Sw/oT8T7ERj7c8ueVA8/v7q8UayGcQ+qqXLmeqwl90EkVSPAIQhlykoF7KIr+jXyb6L7RbohRYs8DviubVzWO+4Y7RIwvD4005UyuOIMWOSYBNYtxqnvSEPSAwnwvEMtQfAPZrLuWgJlwh2z1z7E2srFOZ1dk6WQtRYjOYwwKglzEr8AxTYZk=
  file_glob: true
  file:
  - "dist/dashy-app*.dmg"
  - "dist/dashy-app*.deb"
  - "dist/dashy-app*.snap"
  - "dist/dashy-app*.AppImage"
  - "dist/dashy-app*.exe"
  - "dist/latest*.yml"
  skip_cleanup: true
  on:
    repo: GordonSmith/dashy-app
    tags: true
